version: '3.8'

services:
  bd_tool:
    build:
      context: "./BD Tool"
      dockerfile: Dockerfile
    volumes:
      - "./BD Tool:/app"
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - bd_tool_be

  rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"

  bd_tool_be:
    build:
      context: "./BD Tool BE"
      dockerfile: Dockerfile
    volumes:
      - "./BD Tool BE:/app"
    ports:
      - "8000:8000"
    environment:
      ATLAS_URI: "mongodb://mongodb:27017/"
      DB_NAME: "BD_db"
      SECRET_KEY: "your_secret_key_here"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  node_modules:
