version: '3.8'

services:
  bd_tool:
    build:
      context: "./BD Tool"
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # environment:
    #   VITE_API_URL: "http://localhost:8000"
    depends_on:
      - bd_tool_be

  rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"

  bd_tool_be:
      build:
        context: "./BD Tool BE"
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      environment:
        ATLAS_URI: "mongodb://mongodb:27017/"
        DB_NAME: "BD_db"
        SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
        RABBITMQ_HOST: "rabbitmq"
        RABBITMQ_PORT: 5672
      depends_on:
        - rabbitmq
        - mongodb